// Generated by gencpp from file package1/magnitude.msg
// DO NOT EDIT!


#ifndef PACKAGE1_MESSAGE_MAGNITUDE_H
#define PACKAGE1_MESSAGE_MAGNITUDE_H

#include <ros/service_traits.h>


#include <package1/magnitudeRequest.h>
#include <package1/magnitudeResponse.h>


namespace package1
{

struct magnitude
{

typedef magnitudeRequest Request;
typedef magnitudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct magnitude
} // namespace package1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::package1::magnitude > {
  static const char* value()
  {
    return "55d1a215f43fd1f64eb105a505b172c4";
  }

  static const char* value(const ::package1::magnitude&) { return value(); }
};

template<>
struct DataType< ::package1::magnitude > {
  static const char* value()
  {
    return "package1/magnitude";
  }

  static const char* value(const ::package1::magnitude&) { return value(); }
};


// service_traits::MD5Sum< ::package1::magnitudeRequest> should match
// service_traits::MD5Sum< ::package1::magnitude >
template<>
struct MD5Sum< ::package1::magnitudeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::package1::magnitude >::value();
  }
  static const char* value(const ::package1::magnitudeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::package1::magnitudeRequest> should match
// service_traits::DataType< ::package1::magnitude >
template<>
struct DataType< ::package1::magnitudeRequest>
{
  static const char* value()
  {
    return DataType< ::package1::magnitude >::value();
  }
  static const char* value(const ::package1::magnitudeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::package1::magnitudeResponse> should match
// service_traits::MD5Sum< ::package1::magnitude >
template<>
struct MD5Sum< ::package1::magnitudeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::package1::magnitude >::value();
  }
  static const char* value(const ::package1::magnitudeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::package1::magnitudeResponse> should match
// service_traits::DataType< ::package1::magnitude >
template<>
struct DataType< ::package1::magnitudeResponse>
{
  static const char* value()
  {
    return DataType< ::package1::magnitude >::value();
  }
  static const char* value(const ::package1::magnitudeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACKAGE1_MESSAGE_MAGNITUDE_H
